### ISSUE TITLE
AspenSinterConsumerConsole Fails on Initial Run

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_sci_gate#18]
## Description
AspenSinterConsumerConsole Fails on Initial Run
```
copyFilesToDisk Failed to copy files to working directory: The file test\\1\\BFB_v11_FBS_01_26_2018.acmf\\'already exists.
```
## BACKGROUND
When a new simulation version is uploaded to Turbine it is identified via a GUID.  The AspenSinterConsumer will grab the new version files and download them to its working directory to a directory name GUID.  When that simulation is run the files are copied from the GUID to a new working directory identified by JOB TABLE COUNT ( incrementing job number ).

## PROBLEM
The first time a new simulation is run the cache GUID is created for the simulation.  Some logic error is causing job directory ( eg. 1 ) to have the simulation files written to it twice and this is causing a File Copy Error.  

After the initial failed run the simulation will run correctly and I think the auto reattempt by FOQUS has probably covered this up for a long time.

## TRACEBACK
```
SinterConsumerConsole: >> Waiting 1
top
SinterConsumerRun.Run: Starting
DBJobQueue.GetNext: Get Job for Application: ACM
DBJobQueue.GetNext: Found Job(fdf5eee6-a30e-41fb-9511-dc47b4544691): BFB_v11_FBS
_01_26_2018,ACM
SinterConsumerRun.Run: 10/24/2019 8:33:21 PM - Found JOB(reset): 14
SinterConsumerRun.Run: Setup Sinter Process 14
SinterConsumer: DoSetup Called on 14
ConsumerJobContract: Setup consumer GUID 3d7e3962-033f-42c4-8178-de1b5e98c500
SinterConsumerRun.SetupWorkingDir: The Working directory is: test\14
SinterConsumerRun.CopyFromCache: Copying From Cache: test\e6918e4d-6ce2-4649-905
9-6cd20e59fc8e
SinterConsumerRun.CopyFromCache: Directory test\e6918e4d-6ce2-4649-9059-6cd20e59
fc8e doesn't exist
ConsumerJobContract: FILE: aspenfile
ConsumerJobContract: FILE: BFB_v11_FBS_01_26_2018.acmf
ConsumerJobContract: FILE: configuration
AspenSinterConsumer.copyFilesToDisk: file_version: 0.3
ConsumerJobContract: FILE: aspenfile
ConsumerJobContract: FILE: BFB_v11_FBS_01_26_2018.acmf
ConsumerJobContract: FILE: configuration
ConsumerJobContract: FILE: aspenfile
ConsumerJobContract: FILE: BFB_v11_FBS_01_26_2018.acmf
SinterConsumerRun.DoSetup: copyFilesToDisk Failed to copy files to working direc
tory
SinterConsumerRun.DoSetup: The file 'test\14\BFB_v11_FBS_01_26_2018.acmf' alread
y exists.
SinterConsumerRun.DoSetup:    at System.IO.__Error.WinIOError(Int32 errorCode, S
tring maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Turbine.Consumer.AspenTech.AspenSinterConsumer.copyFilesToDisk(IJobConsume
rContract job) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_s
ci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 121
   at Turbine.Consumer.SimSinter.SinterConsumerRun.DoSetup(IJobConsumerContract
job) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Ma
ster\Turbine.Consumer.SimSinter\SinterConsumerRun.cs:line 398
SinterConsumerConsole: Exception caught from Run: One or more errors occurred.
SinterConsumerConsole:    at System.Threading.Tasks.Task.ThrowIfExceptional(Bool
ean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   at Turbine.Consumer.Console.SinterConsumerConsole.Run() in c:\Users\boverhof\
Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Cons
ole\SinterConsumerConsole.cs:line 248
SinterConsumerConsole: InnerException: System.IO.IOException: The file 'test\14\
BFB_v11_FBS_01_26_2018.acmf' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Turbine.Consumer.AspenTech.AspenSinterConsumer.copyFilesToDisk(IJobConsume
rContract job) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_s
ci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 121
   at Turbine.Consumer.SimSinter.SinterConsumerRun.DoSetup(IJobConsumerContract
job) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Ma
ster\Turbine.Consumer.SimSinter\SinterConsumerRun.cs:line 407
   at Turbine.Consumer.SimSinter.SinterConsumerRun.Run() in c:\Users\boverhof\Do
cuments\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.SimSin
ter\SinterConsumerRun.cs:line 945
   at Turbine.Consumer.Console.SinterConsumerConsole.<Run>b__4() in c:\Users\bov
erhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consume
r.Console\SinterConsumerConsole.cs:line 186
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
SinterConsumerConsole: Stop called
SinterConsumerConsole: > New Task
SinterConsumerRun.Run: Starting
DBJobQueue.GetNext: Get Job for Application: ACM
top
DBJobQueue.GetNext: Get Job for Application: AspenPlus
SinterConsumerRun.Run: 10/24/2019 8:33:23 PM - No submitted jobs in queue
```

**Comment by boverhof** [comment]
Additionally it appears when I terminate ( control-C ) the `AspenSinterConsumerConsole.exe` process after a successful run the `am_task_server.exe` ACM process is still running.
<img width="797" alt="Screen Shot 2019-10-24 at 1 17 49 PM" src="https://user-images.githubusercontent.com/738295/67522065-e3c2d280-f660-11e9-80e4-b65de96f44e1.png">

**Comment by boverhof** [comment]
Will grab the older non-FIPS compliant TurbineLite.msi and install to see if the problem is with the newest release only.

**Comment by fsoepyan** [comment]
To test FOQUS and Turbine to see if this is still an issue:
Can you please let me know which version of FOQUS and which version of Turbine I should use?
Thank you.

**Comment by ksbeattie** [comment]
@anujad95 and @jmorgan29 have verified that this is fixed using the latest version of Turbine.
